---
title: "GoogleAirportSearchTrends"
author: "Chad Loh"
date: '2022-04-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("PMassicotte/gtrendsR")
library(gtrendsR)
library(tidyverse)
```



## Data Preparation

"now 1-H" Last hour
"now 4-H" Last four hours
"now 1-d" Last day
"now 7-d" Last seven days
"today 1-m" Past 30 days
"today 3-m" Past 90 days
"today 12-m" Past 12 months
"today+5-y" Last five years (default)
"all" Since the beginning of Google Trends (2004)
"Y-m-d Y-m-d" Time span between two dates (ex.: "2010-01-01 2010-04-03")
```{r import airport data}
airports <- read.csv('data/airports_enplanements.csv')
airports.wiki <- read.csv('data/airports_wiki.csv')

airports$Enplanements <- as.numeric(gsub(",", "", airports$Enplanements))

airports <- airports %>% 
  top_n(300, Enplanements)

head(airports)
head(airports.wiki)
```

```{r join datasets}

a_num = 250

airport.df <- left_join(airports, airports.wiki, by = c("IATA" = "iata_code")) %>%
  select(IATA, State, City, name, latitude_deg, longitude_deg, municipality, Enplanements) %>%
  filter(!is.na(name)) %>%
  top_n(a_num, Enplanements)

head(airport.df)

top_airports <- unlist(airport.df$IATA)
           
```


```{r}
res = data.frame()

for (i in 1:10){
  res0 <- gtrends(top_airports[i], geo = "US")
  res <- rbind(res, res0$interest_by_dma)
}

gtrends("Mcdonalds", geo = "US")

```

```{r}
res
```


